python train.py --name celeba_styleD --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Synthesized/Images_60 --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Synthesized/mask_60 --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 320 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3
python train.py --name celeba_styleD --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/TFill/examples/celeba/img --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/TFill/examples/celeba/mask --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 320 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3
python train.py --name MaskAway_styleD --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Synthesized/Images_60 --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Synthesized/mask_60 --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3 --no_flip


# FFHQ-trained from scratch
python train.py --name M2_FFHQ_from_scratch --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k_masks --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3 --no_flip

# after 770000 iterations we got rid of the add_noise flag
python train.py --name M2_FFHQ_from_scratch --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k_masks --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3 --no_flip
python train.py --name M2_FFHQ_from_scratch --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k_masks --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --display_ncols 0 --continue_train --mask_type 3 --no_flip

# FFHQ pretrained
python train.py --name M3_FFHQ_pretrained --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k_masks --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 0 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --add_noise --display_ncols 0 --continue_train --mask_type 3 --no_flip
python train.py --name M3_FFHQ_pretrained --img_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k --mask_file E:/1-EngSci3/1-ECE324/Triple-Dots/Datasets/FFHQ512_10k_masks --model tc --coarse_or_refine refine --netT original --n_encoders 12 --n_decoders 10 --netD style --gpu_ids 0 --load_size 257 --fine_size 256 --batch_size 4 --display_port 8097 --attn_G --display_ncols 0 --continue_train --mask_type 3 --no_flip

